# Generated by Django 2.1 on 2021-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='cor',
            field=models.ManyToManyField(to='ecommerce.Cores'),
        ),
    ]
