# Generated by Django 2.1 on 2021-03-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20210318_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='categoria',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cores',
            name='cor',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
