# Generated by Django 2.1 on 2021-03-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20210318_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['categoria']},
        ),
        migrations.AlterModelOptions(
            name='cores',
            options={'ordering': ['cor']},
        ),
    ]
