# Generated by Django 2.1 on 2021-03-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20210322_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(choices=[('m', 'Masculino'), ('m', 'Feminino'), ('outros', 'Outros')], max_length=1),
        ),
    ]
