# Generated by Django 2.1 on 2021-03-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20210322_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='quantidade_vendida',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
