# Generated by Django 2.1 on 2021-03-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_produtos_quantidade_vendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
