# Generated by Django 2.1 on 2021-03-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_clientes_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
