# Generated by Django 2.1 on 2021-03-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20210323_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='quantidade_vendida',
        ),
    ]
