# Generated by Django 2.1 on 2021-03-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_remove_produtos_quantidade_vendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='quantidade_vendida',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
