# Generated by Django 2.1 on 2021-04-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_produtos_quantidade_vendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='especificacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade_vendida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
