# Generated by Django 2.1 on 2021-04-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_auto_20210405_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='percentual_desconto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_desconto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
